export const TRACKING_PARAMETER_PREFIXES = [
	'elq',
	'hsa_',
	'mtm_',
	'pk_',
	'trk',
	'utm_',
] as const;

export const TRACKING_PARAMETER_NAMES = [
	'__s',
	'_ga',
	'_gl',
	'_hsenc',
	'_hsmi',
	'ad_id',
	'adgroup',
	'adgroup_id',
	'adgroupid',
	'adid',
	'adset_id',
	'adsetid',
	'aff',
	'aff_id',
	'affid',
	'affiliate',
	'affiliate_id',
	'affiliateid',
	'campaign',
	'campaign_id',
	'campaignid',
	'cid',
	'cmpid',
	'dclid',
	'epik',
	'fbclid',
	'feature',
	'gad_campaignid',
	'gad_source',
	'gbraid',
	'gclid',
	'gclsrc',
	'hsctatracking',
	'icid',
	'igshid',
	'irclickid',
	'ko_click_id',
	'li_fat_id',
	'lipi',
	'mc_cid',
	'mc_eid',
	'mibextid',
	'midsig',
	'midtoken',
	'mkt_tok',
	'ml_subscriber',
	'ml_subscriber_hash',
	'msclkid',
	'ocid',
	'oly_anon_id',
	'oly_enc_id',
	'omnisendcontactid',
	'partner',
	'partner_id',
	'partnerid',
	'rb_clickid',
	'ref',
	'ref_',
	'referrer',
	'refid',
	's_cid',
	'scid',
	'share',
	'share_id',
	'shareid',
	'si',
	'source',
	'spm',
	'src',
	'srsltid',
	'tag',
	'trackingid',
	'ttclid',
	'twclid',
	'vero_conv',
	'vero_id',
	'wbraid',
	'wickedid',
	'wt.mc_id',
	'yclid',
] as const;

const trackingParameterNames = new Set<string>(TRACKING_PARAMETER_NAMES);

export function isTrackingParameter(parameterName: string): boolean {
	const normalizedName = parameterName.toLowerCase();

	return (
		trackingParameterNames.has(normalizedName) ||
		TRACKING_PARAMETER_PREFIXES.some((prefix) => normalizedName.startsWith(prefix))
	);
}
